# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Study/hardware/zonghe1/zonghe1.srcs/sources_1/ip/gly_0/gly_0.xci
# IP: The module: 'gly_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Study/hardware/zonghe1/zonghe1.srcs/sources_1/ip/gly_0/src/cordic_ip_1/cordic_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_ip || ORIG_REF_NAME==cordic_ip} -quiet] -quiet

# IP: d:/Study/hardware/zonghe1/zonghe1.srcs/sources_1/ip/gly_0/src/fifo_ip_1/fifo_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_ip || ORIG_REF_NAME==fifo_ip} -quiet] -quiet

# XDC: d:/Study/hardware/zonghe1/zonghe1.srcs/sources_1/ip/gly_0/src/fifo_ip_1/fifo_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_ip || ORIG_REF_NAME==fifo_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: d:/Study/hardware/zonghe1/zonghe1.srcs/sources_1/ip/gly_0/gly_0.xci
# IP: The module: 'gly_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Study/hardware/zonghe1/zonghe1.srcs/sources_1/ip/gly_0/src/cordic_ip_1/cordic_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_ip || ORIG_REF_NAME==cordic_ip} -quiet] -quiet

# IP: d:/Study/hardware/zonghe1/zonghe1.srcs/sources_1/ip/gly_0/src/fifo_ip_1/fifo_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_ip || ORIG_REF_NAME==fifo_ip} -quiet] -quiet

# XDC: d:/Study/hardware/zonghe1/zonghe1.srcs/sources_1/ip/gly_0/src/fifo_ip_1/fifo_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_ip || ORIG_REF_NAME==fifo_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
