set_property PACKAGE_PIN H16 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports {data_rd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_rd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_rd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_rd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property PACKAGE_PIN V17 [get_ports scl]
set_property PACKAGE_PIN V18 [get_ports sda]
set_property PACKAGE_PIN M14 [get_ports {state[3]}]
set_property PACKAGE_PIN N16 [get_ports {state[2]}]
set_property PACKAGE_PIN P14 [get_ports {state[1]}]
set_property PACKAGE_PIN R14 [get_ports {state[0]}]
set_property PACKAGE_PIN A20 [get_ports {state[7]}]
set_property PACKAGE_PIN B19 [get_ports {state[6]}]
set_property PACKAGE_PIN B20 [get_ports {state[5]}]
set_property PACKAGE_PIN C20 [get_ports {state[4]}]
set_property PACKAGE_PIN E17 [get_ports {data_rd[7]}]
set_property PACKAGE_PIN E18 [get_ports {data_rd[6]}]
set_property PACKAGE_PIN E19 [get_ports {data_rd[5]}]
set_property PACKAGE_PIN F16 [get_ports {data_rd[4]}]
set_property PACKAGE_PIN F17 [get_ports {data_rd[3]}]
set_property PACKAGE_PIN F20 [get_ports {data_rd[2]}]
set_property PACKAGE_PIN G14 [get_ports {data_rd[1]}]
set_property PACKAGE_PIN G15 [get_ports {data_rd[0]}]

set_property PACKAGE_PIN U12 [get_ports spi_clk]
set_property PACKAGE_PIN U13 [get_ports spi_cs]
set_property PACKAGE_PIN T14 [get_ports spi_dc]
set_property PACKAGE_PIN V13 [get_ports spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports spi_dc]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]

set_property PACKAGE_PIN V15 [get_ports spi_rst]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rst]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txd]
set_property PACKAGE_PIN T15 [get_ports uart_rtl_rxd]
set_property PACKAGE_PIN R16 [get_ports uart_rtl_txd]






set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txd]

set_property PACKAGE_PIN R16 [get_ports uart_rtl_txd]
set_property PACKAGE_PIN T15 [get_ports uart_rtl_rxd]
